//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricCarDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Battery
    {
        public int Id { get; set; }
        public Nullable<int> btId { get; set; }
        public string state { get; set; }
    
        public virtual BatteryType BatteryType { get; set; }
    }
}
