//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricCarDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Booking = new HashSet<Booking>();
        }
    
        public int Id { get; set; }
        public Nullable<int> dgId { get; set; }
    
        public virtual ICollection<Booking> Booking { get; set; }
        public virtual Person Person { get; set; }
        public virtual DiscoutGroup DiscoutGroup { get; set; }
    }
}
