//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricCarDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public Station()
        {
            this.BatteryStorages = new HashSet<BatteryStorage>();
            this.BookingLines = new HashSet<BookingLine>();
            this.Connections = new HashSet<Connection>();
            this.Connections1 = new HashSet<Connection>();
            this.Employees = new HashSet<Employee>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string country { get; set; }
        public string state { get; set; }
    
        public virtual ICollection<BatteryStorage> BatteryStorages { get; set; }
        public virtual ICollection<BookingLine> BookingLines { get; set; }
        public virtual ICollection<Connection> Connections { get; set; }
        public virtual ICollection<Connection> Connections1 { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
