//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricCarDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Period
    {
        public int bsId { get; set; }
        public System.DateTime time { get; set; }
        public Nullable<int> avaiNumber { get; set; }
        public Nullable<int> custBookNumber { get; set; }
    
        public virtual BatteryStorage BatteryStorage { get; set; }
    }
}
