//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricCarDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.BookingLine = new HashSet<BookingLine>();
            this.Station = new HashSet<Station>();
        }
    
        public int Id { get; set; }
        public Nullable<int> cId { get; set; }
        public Nullable<decimal> totalPrice { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> tripStart { get; set; }
        public string creaditCard { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<BookingLine> BookingLine { get; set; }
        public virtual ICollection<Station> Station { get; set; }
    }
}
