//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricCarDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ElectricCarEntities : DbContext
    {
        public ElectricCarEntities()
            : base("name=ElectricCarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Battery> Batteries { get; set; }
        public DbSet<BatteryStorage> BatteryStorages { get; set; }
        public DbSet<BatteryType> BatteryTypes { get; set; }
        public DbSet<Booking> Bookings { get; set; }
        public DbSet<BookingLine> BookingLines { get; set; }
        public DbSet<Connection> Connections { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<DiscoutGroup> DiscoutGroups { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<LoginInfo> LoginInfoes { get; set; }
        public DbSet<Period> Periods { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<Station> Stations { get; set; }
    }
}
