//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricCarDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.LoginInfo = new HashSet<LoginInfo>();
        }
    
        public int Id { get; set; }
        public string fName { get; set; }
        public string lname { get; set; }
        public string address { get; set; }
        public string country { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string pType { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<LoginInfo> LoginInfo { get; set; }
    }
}
