//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricCarDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public Station()
        {
            this.BatteryStorage = new HashSet<BatteryStorage>();
            this.Connection = new HashSet<Connection>();
            this.Connection1 = new HashSet<Connection>();
            this.Employee = new HashSet<Employee>();
            this.Booking = new HashSet<Booking>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string country { get; set; }
        public string state { get; set; }
    
        public virtual ICollection<BatteryStorage> BatteryStorage { get; set; }
        public virtual ICollection<Connection> Connection { get; set; }
        public virtual ICollection<Connection> Connection1 { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
        public virtual ICollection<Booking> Booking { get; set; }
    }
}
